apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: systems-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: block-vol-storageclass
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - image: ghcr.io/seagate/seagate-exos-x-testapp
    command: ["/bin/sh", "-c", "while sleep 60; do echo hello > /vol/test && ls -l /vol && cat /vol/test && rm /vol/test; done"]
    name: test-pod-container
    volumeDevices:
    - devicePath: /block-vol
      name: volume
    ports:
    - containerPort: 8080
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: systems-pvc