apiVersion: v1
kind: Secret
metadata:
  name: seagate-exos-x-csi-secrets
  namespace: default
type: Opaque
data:
  apiAddress: aHR0cDovLzxpcGFkZHJlc3M+ # base64 encoded api address 'http://<ipaddress>'
  username: dXNlcm5hbWU= # base64 encoded 'username'
  password: cGFzc3dvcmQ= # base64 encoded 'password'
  CHAPusername: ZXhhbXBsZVVzZXJuYW1l # base64 'exampleUsername'. The CHAP username
  CHAPpassword: ZXhhbXBsZXNlY3JldA== # base64 'examplesecret'. The secret that the recipient uses to authenticate the originator. The secret is case sensitive and can include from 12 to 16 bytes. The value can include spaces and printable UTF-8 characters except: " <
  CHAPusernameIn: aXFuLjE5OTItMDkuY29tLmV4YW1wbGU6MDEuYXJyYXkuMDAxMjM0YQ== # base64 'iqn.1992-09.com.example:01.array.001234a'. The target name, typically in IQN format. This value is optional, used for Mutual CHAP.
  CHAPpasswordIn: bXV0dWFsc2VjcmV0 # base64 encoded 'mutualsecret'.  The secret is case sensitive, can include from 12 to 16 bytes, and must differ from the originator secret. This value is optional, used for Mutual CHAP