apiVersion: v1
kind: Secret
metadata:
  name: seagate-exos-x-csi-secrets
  namespace: default
type: Opaque
data:
  apiAddress: aHR0cDovLzxpcGFkZHJlc3M+ # base64 encoded api address 'http://<ipaddress>'
  apiAddressB: aHR0cDovLzxpcGFkZHJlc3M+ # Optional second base64 encoded api address 'http://<ipaddress>'
  username: dXNlcm5hbWU= # base64 encoded 'username'
  password: cGFzc3dvcmQ= # base64 encoded 'password'
