apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: csi-exos-x.seagate.com
allowVolumeExpansion: true
metadata:
  name: storageclass-seagate
parameters:
  csi.storage.k8s.io/provisioner-secret-name: secret-seagate
  csi.storage.k8s.io/provisioner-secret-namespace: seagate
  csi.storage.k8s.io/controller-publish-secret-name: secret-seagate
  csi.storage.k8s.io/controller-publish-secret-namespace: seagate
  csi.storage.k8s.io/controller-expand-secret-name: secret-seagate
  csi.storage.k8s.io/controller-expand-secret-namespace: seagate
  fsType: ext4 # Desired filesystem
  pool: A # Pool for volumes provisioning
  volPrefix: stx # Desired prefix for volume naming, an underscore is appended
  storageProtocol: sas # The storage interface (iscsi, fc, sas) being used for storage i/o
allowedTopologies:
  - matchLabelExpressions:
    - key: com.seagate-exos-x-csi/sas-address-0
      values:
      - 500605b00b4ec831 # The first sas initiator on your node
