kind: Deployment
apiVersion: apps/v1
metadata:
  name: seagate-exos-x-csi-controller-server
  labels:
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: dynamic-provisionning-controller
{{ include "csidriver.labels" . | indent 4 }}

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: seagate-exos-x-csi-controller-server
{{ include "csidriver.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        app: seagate-exos-x-csi-controller-server
{{ include "csidriver.labels" . | indent 8 }}
    spec:
      serviceAccount: csi-provisioner
      containers:
        - name: seagate-exos-x-csi-controller
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          command:
            - seagate-exos-x-csi-controller
            - -bind=unix:///csi/csi.sock
{{- include "csidriver.extraArgs" .Values.controller | indent 10 }}
          env:
            - name: EXOS-X-CSI-NODE-SERVICE-PORT
              value: "978"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: csi-run-dir
              mountPath: /var/run/csi-exos-x.seagate.com
          ports:
            - containerPort: 9842
              name: metrics
              protocol: TCP
        - name: csi-provisioner
          image: {{ .Values.csiProvisioner.image.repository }}:{{ .Values.csiProvisioner.image.tag }}
          args:
            - --csi-address=/csi/csi.sock
            - --worker-threads=1
            - --timeout={{ .Values.csiProvisioner.timeout }}
{{- include "csidriver.extraArgs" .Values.csiProvisioner | indent 10 }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-attacher
          image: {{ .Values.csiAttacher.image.repository }}:{{ .Values.csiAttacher.image.tag }}
          args:
            - --csi-address=/csi/csi.sock
            - --worker-threads=1
            - --timeout={{ .Values.csiAttacher.timeout }}
{{- include "csidriver.extraArgs" .Values.csiAttacher | indent 10 }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-resizer
          image: {{ .Values.csiResizer.image.repository }}:{{ .Values.csiResizer.image.tag }}
          args:
            - --csi-address=/csi/csi.sock
{{- include "csidriver.extraArgs" .Values.csiResizer | indent 10 }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-snapshotter
          image: {{ .Values.csiSnapshotter.image.repository }}:{{ .Values.csiSnapshotter.image.tag }}
          args:
            - --csi-address=/csi/csi.sock
{{- include "csidriver.extraArgs" .Values.csiSnapshotter | indent 10 }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
        - name: socket-dir
          emptyDir:
            medium: Memory
        - name: csi-run-dir
          hostPath:
            path: /var/run/csi-exos-x.seagate.com
